dofile(minetest.get_modpath("food").."/spices.lua")
dofile(minetest.get_modpath("food").."/applesauce.lua")
dofile(minetest.get_modpath("food").."/sugar.lua")
dofile(minetest.get_modpath("food").."/salt.lua")
dofile(minetest.get_modpath("food").."/mushrooms.lua")
dofile(minetest.get_modpath("food").."/crafting.lua")